const frases = [
    "Mateus 22:37-39  Ame o Senhor, o seu Deus, de todo o seu coração... e ame o seu próximo como a si mesmo.",
    "Salmos 23:1  O Senhor é o meu pastor; nada me faltará.",
    "Filipenses 4:13  Posso todas as coisas naquele que me fortalece.",
    "João 3:16  Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.",
    "Jeremias 29:11  Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de lhes causar dano, planos de dar a vocês esperança e um futuro.",
    "Provérbios 3:5-6  Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.",
    "Isaías 41:10  Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    "Mateus 6:33  Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.",
    "Romanos 8:28  Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados segundo o seu propósito.",
    "2 Coríntios 5:7  Porque vivemos por fé, e não pelo que vemos.",
    "Josué 1:9  Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    "Salmos 46:1  Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.",
    "Hebreus 11:1  Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.",
    "Romanos 12:2  Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.",
    "Mateus 11:28  Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.",
    "Salmos 91:1  Aquele que habita no esconderijo do Altíssimo e descansa à sombra do Todo-Poderoso.",
    "João 14:6  Respondeu Jesus: 'Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.'",
    "Tiago 1:5  Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.",
    "1 Coríntios 13:4-7  O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha...",
    "Gálatas 5:22-23  Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio.",
    "Efésios 6:10  Finalmente, fortaleçam-se no Senhor e no seu forte poder.",
    "Salmos 37:4  Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.",
    "Provérbios 16:3  Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.",
    "Romanos 15:13  Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele.",
    "Mateus 5:14  Vocês são a luz do mundo. Não se pode esconder uma cidade construída sobre um monte.",
    "1 Pedro 5:7  Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
    "Filipenses 4:6  Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus.",
    "Hebreus 13:8  Jesus Cristo é o mesmo ontem, hoje e para sempre.",
    "Salmos 34:8  Provem, e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!",
    "João 16:33  Eu disse essas coisas para que em mim vocês tenham paz. Neste mundo vocês terão aflições; contudo, tenham ânimo! Eu venci o mundo.",
    "Colossenses 3:23  Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens.",
    "Romanos 5:8  Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.",
    "2 Timóteo 1:7  Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.",
    "Atos 16:31  Creia no Senhor Jesus, e serão salvos, você e os de sua casa.",
    "Salmos 19:1  Os céus declaram a glória de Deus; o firmamento proclama a obra das suas mãos.",
    "Tiago 4:7  Portanto, submetam-se a Deus. Resistam ao diabo, e ele fugirá de vocês.",
    "1 João 4:18  No amor não há medo; ao contrário, o perfeito amor expulsa o medo.",
    "Isaías 40:31  Mas aqueles que esperam no Senhor renovam as suas forças.",
    "1 Coríntios 10:31  Assim, quer vocês comam, bebam ou façam qualquer outra coisa, façam tudo para a glória de Deus.",
    "Deuteronômio 31:6  Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados, pois o Senhor, seu Deus, vai com vocês.",
    "Salmos 121:1-2  Elevo os meus olhos para os montes; de onde me vem o socorro? Meu socorro vem do Senhor.",
    "João 8:12  Eu sou a luz do mundo. Quem me segue nunca andará em trevas.",
    "Romanos 10:9  Se você confessar com a sua boca que Jesus é Senhor e crer no seu coração que Deus o ressuscitou, será salvo.",
    "Isaías 26:3  Tu guardarás em perfeita paz aquele cujo propósito está firme, porque em ti confia.",
    "Salmos 55:22  Entregue suas preocupações ao Senhor, e ele o susterá.",
    "1 Tessalonicenses 5:16-18  Alegrem-se sempre. Orem continuamente. Dêem graças em todas as circunstâncias.",
    "Provérbios 18:10  O nome do Senhor é uma torre forte; os justos correm para ela e estão seguros.",
    "Gênesis 1:1 No princípio Deus criou os céus e a terra.",
    "Mateus 28:20  E eu estarei sempre com vocês, até o fim dos tempos.",
    "Hebreus 4:12 Pois a palavra de Deus é viva e eficaz.",
];

function mostrarFrase() {
    const indice = Math.floor(Math.random() * frases.length);
    document.getElementById("frase").innerText = frases[indice];
}
